version: '3.7'

services:
  traefik:
    command: --api.insecure=true --providers.docker 
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_UI_PORT}:8080
    labels:
      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-host.rule=Host(`${SERVICE_NAME}.${APP_PREFIX}.localhost`)
      - traefik.http.services.${APP_PREFIX}-${SERVICE_NAME}.loadbalancer.server.port=8080
